### ISSUE TITLE
Ability to remove player join messages in hypixel lobbies

### ISSUE THREAD

**Issue by moehreag** [moehreag/AxolotlClient-branding#102]
https://github.com/AxolotlClient/AxolotlClient-mod/issues/13#issuecomment-1642903972

**Comment by yourmotheriskoi** [comment]
if possible, could strings be added for the spanish language and possibly others? lobby join messages in hypixel spanish are,
_____ se ha unido al lobby!
thank you.

**Comment by CodeSyntaxCreator** [comment]
Apparently it is possible
