### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by Cuteistfox** [moehreag/AxolotlClient-branding#113]
it has some network optimizatiotion that are good for pvping on low bandwith connection so you might want to update

**Comment by moehreag** [comment]
QFAPI has not yet been released for 1.20.2. While a release would be possible with the snapshot release of QSL, users are currently unable to download it since it is only packaged together with QFAPI.

**Comment by Cuteistfox** [comment]
i just noticed that the QFAPI isnt there

**Comment by Cuteistfox** [comment]
tag as upstream
