### ISSUE TITLE
Crash on booting 1.16-combat-6

### ISSUE THREAD

**Issue by Cuteistfox** [moehreag/AxolotlClient-branding#116]
logs:https://mclo.gs/jpco8wj
other mods:see logs
am i a cat:yes
steps to repruduce: bott up with these mods(mods fromm [nexia's list](github.com/nexia-cts/cts-mod-list))(for creating a multimc instance just before hiting install quit/fabric put in 

{
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.fabricmc:intermediary:1.16_combat-6",
            "url": "https://maven.fabric.rizecookey.net/"
        }
    ],
    "name": "Intermediary Mappings",
    "releaseTime": "2021-11-20T05:54:29+0100",
    "requires": [
        {
            "equals": "1.16_combat-6",
            "uid": "net.minecraft"
        }
    ],
    "type": "release",
    "uid": "net.fabricmc.intermediary",
    "version": "1.16_combat-6",
    "volatile": true
}

 in a file named `net.fabricmc.intermediary.json`
am i trying diisableing mods:no bit i will in a few hours

### _**task list**_

- [x] have me try disableing mods
- [x] FIgure bug
- [x] fix it

**Comment by moehreag** [comment]
remove memoryleakfix

**Comment by Cuteistfox** [comment]
ill go make a pr to put memory leak fix in the breaks section of the mod.json

**Comment by Cuteistfox** [comment]
merge #117 to have this mod not work with memoryleakfix
