### ISSUE TITLE
FEAture request: Use the (quilted)fabric apis system for registering Key binds

### ISSUE THREAD

**Issue by Cuteistfox** [moehreag/AxolotlClient-branding#121]
When im trying to setup zoom in cntrolify for example axoltils zoom dosent show up also i cant modify alll my keybinds from one page

**Comment by moehreag** [comment]
While all the keybinds are going to return to the controls settings with the config library rewrite, the APIs are not going to be used for that :).

**Comment by Cuteistfox** [comment]
why?

**Comment by moehreag** [comment]
In order to reduce required libraries, and this is a case where not using the API does not increase incompatibilities with other mods. Where it is relevant for compatibility (e.g. in 1.8) the API is used. However, f.e. on 1.20.x the api purely serves as a tool for registration.

**Comment by Cuteistfox** [comment]
will it still work with controlify for binding controlers and wil it  work with amecs?

**Comment by moehreag** [comment]
I don't see why it wouldn't, it works the same as fabric's system so unless these mods use internals it should work (in a future release)

**Comment by Cuteistfox** [comment]
good
