### ISSUE TITLE
Crash Minecraft 1.8.9

### ISSUE THREAD

**Issue by ghost** [moehreag/AxolotlClient-branding#125]
Minecraft crashes immediately when running.

[2024-02-11-7.log](https://github.com/AxolotlClient/AxolotlClient-mod/files/14233121/2024-02-11-7.log)

client:polymc 6.1
version:ornithe-1.8.9
mods:
axolotl client-3.0.6+1.8.9
legacy fabric api-1.9.1
legacy lwjgl3-1.1.7+1.8.9
mod menu ornithe-0.2.1+mc1.8.9
ornithe standard libraries-0.13.3

It should be noted that it has been tested with version 1.9.0 of the legacy fabric api and it seems that it does not run because of the api. (Maybe it interferes with ornithe.)

**Comment by moehreag** [comment]
the version you are running is not compatible with ornithe (yet). Please also try to use Prism Launcher instead of PolyMC if possible and make sure to only run mods for ornithe **or** legacy-fabric.

**Comment by ghost** [comment]
> the version you are running is not compatible with ornithe (yet).
Is there another version that is compatible with ornithe?

**Comment by moehreag** [comment]
> > the version you are running is not compatible with ornithe (yet).
> Is there another version that is compatible with ornithe?

There currently is no version for ornithe that is publicly released.
