### ISSUE TITLE
Releases of the client as a modpack to support MultiMC or PolyMC (i can handle this if you allow me btw)

### ISSUE THREAD

**Issue by moehreag** [moehreag/AxolotlClient-branding#18]
@YakisikliBaran yes you are allowed to, I'll try to always keep the mod up-to-date on modrinth.

**Comment by ghost** [comment]
@moehreag Alright,i am not in Istanbul right now however there is this laptop i can work on.But i dunno who used it before but installed some spyware(Windows 10 Driver apps,also the os itself) so we will be getting an new usb to install pop os on this pc.
Until that i wont login to my microsoft account for now.
