### ISSUE TITLE
Client crashes 

### ISSUE THREAD

**Issue by ghost** [moehreag/AxolotlClient-branding#34]
Client crashes everytime i try to open the Zoom Options inside of the Axolotl Client Options
Zoom works tho
[latest.log](https://github.com/AxolotlClient/AxolotlClient-mod/files/9832640/latest.log)
[crash-2022-10-20_19.41.52-client.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/9832641/crash-2022-10-20_19.41.52-client.txt)

**Comment by ghost** [comment]
Nvm,seems like the issue found an solution on the discord server.

**Comment by moehreag** [comment]
Fixed in https://github.com/AxolotlClient/AxolotlClient-mod/commit/c44589912a4fae7d3752f0f3340aeb2c3edb79e7 (1.8.9) and https://github.com/AxolotlClient/AxolotlClient-mod/commit/2b6ff6dbd11e095c02c49d518a4c590bfc5dfbdd (1.19.2)
