### ISSUE TITLE
[1.8.9] Mod Menu's button was unable to show

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#48]

**Comment by moehreag** [comment]
could you please provide a little more information (e.g logs)?

**Comment by HowardZHY** [comment]
There isn't any output errors. There only SP, MP and AClient Settings three big buttons on main menu.

https://github.com/HowardZHY/Legacy-Mod-Menu/actions/runs/3759087183/jobs/6388214428 Mod Menu I've fixed for latest LF

**Comment by moehreag** [comment]
I think you made some mistakes when fixing the ModMenu, f.ex. `renderBg(…)` does not have the same function as `mouseDragged(…)`, the `version` field in the fmj is for the mod version, not the minecraft version...

**Comment by HowardZHY** [comment]
I was unable to find renderBg, I thought it might had a wrong name

**Comment by HowardZHY** [comment]
there was another similar method 's param also (client, x, y). I got a stackflow error with that so I use mouseDragged

**Comment by HowardZHY** [comment]
m	(Lave;II)V	b	method_893	renderBg 
yarn 382

method_893 | mouseDragged
yarn 446

and I don't think I need to fix that version; The mod version had been decleared in gradle properties / file name

**Comment by moehreag** [comment]
fixed in <https://github.com/AxolotlClient/AxolotlClient-mod/commit/b803e30f22d98d3e0a855d4a5b6080c2a853eab5>
