### ISSUE TITLE
[1.8.9] NPE when tried to change keybind

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#49]
[crash-2022-12-23_02.03.10-client.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/10289403/crash-2022-12-23_02.03.10-client.txt)

**Comment by moehreag** [comment]
Redownload the mod or get the file from github releases, this should be fixed as of <https://github.com/AxolotlClient/AxolotlClient-mod/commit/c2abd9569aa6cad2a5b5e29d56394e041fa9eb4c> (even though it seemingly has nothing to do with it). The fix has been proven to be working on discord, where this was reported originally.

**Comment by HowardZHY** [comment]
I just got it from github release

**Comment by moehreag** [comment]
hmm.. maybe that file needs to be updated, but the modrinth file should work anyways.

**Comment by HowardZHY** [comment]
now I just downloaded it from modrinth. It's not working too

**Comment by HowardZHY** [comment]
[crash-2022-12-23_02.40.33-client.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/10289590/crash-2022-12-23_02.40.33-client.txt)

**Comment by moehreag** [comment]
i don't know what else could cause this, could you try building the latest commit and see if it still crashes? if this is the case it might be a caching issue as well.

**Comment by moehreag** [comment]
you're correct with the method, even though it really doesn't make any sense to name it that.
(<https://github.com/Legacy-Fabric/yarn/pull/256/files#diff-e7628cb595b82787e98caa4ddc21b2c0b74dc921adb2668a5f8ad9425bc89815>)

**Comment by HowardZHY** [comment]
damn, it only happen with Mod Menu

**Comment by HowardZHY** [comment]
The weird point is both modmenu y ur client has no mixin did thing about class_1802 and class_390

**Comment by moehreag** [comment]
yeah! (but the crash, that did exist, was fixed by the commit mentioned far above already even when it does not make sense to why that fixed it)

**Comment by HowardZHY** [comment]
https://github.com/HowardZHY/Legacy-Mod-Menu/issues/1
