### ISSUE TITLE
[1.8.9] Can't Drag mouse ingame

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#50]
latest build from github actions

**Comment by moehreag** [comment]
again, could you please elaborate, and, if possible, add information on how to reproduce the issue

**Comment by HowardZHY** [comment]
just enter singleplayer world and found your mouse can;t move fov



At 2022-12-23 22:37:08, "moehreag" ***@***.***> wrote:

again, could you please elaborate, and, if possible, add information on how to reproduce the issue

**Comment by moehreag** [comment]
you might have activated the "Rotation Lock" feature by accidentally pressing "P" (default keybind). You can change/unbind the key in Hypixel Mods -> Skyblock if needed, and also disable the toggle if it's on.

**Comment by HowardZHY** [comment]
let me see



At 2022-12-24 00:50:47, "moehreag" ***@***.***> wrote:

you might have activated the "Rotation Lock" feature by accidentally pressing "P" (default keybind). You can change/unbind the key in Hypixel Mods -> Skyblock if needed, and also disable the toggle if it's on.
