### ISSUE TITLE
Tab cmd autofill bug

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#51]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/96782166/209416858-e9f0f52e-7ead-4969-840c-bfbfe90f633e.png">

These autofill msgs are invalid with /tp cmd so it shouldn't be shown

**Comment by moehreag** [comment]
Yes the commands system in 1.8.9 has bugs. And yes, there is no official api for that.

**Comment by HowardZHY** [comment]
: (
maybe a way to disable axolotlclient.* msgs with normal cmds?

**Comment by moehreag** [comment]
should be fixed in <https://github.com/AxolotlClient/AxolotlClient-mod/commit/eee3a3d035b0f4ef0fa6932db73f47a76633c6c6>, please test it and lmk if it has the desired effect.
