### ISSUE TITLE
Remove Freelook on your mod

### ISSUE THREAD

**Issue by RoonMoonlight** [moehreag/AxolotlClient-branding#52]
> We do not endorse nor support cheats/hacks. If you feel like one or more options packaged by this mod could be regarded as one of the above, please let us know and we'll remove said options.

As this description exists I decided to create this issue. I've just noticed that Freelook exists on this mod, which is being forbidden on most pvp servers. And I think this feature should be removed as it can gain unfair advantages by altering the player's perspective, compared with using vanilla perspective feature. The most thing I am concerned is that moderator from community server can ban you for using AxolotlClient because of this feature.

Please consider removing the Freelook on future updates, or I will have to use other similar mod...

**Comment by TheKodeToad** [comment]
Why not just have a server API for servers to ban it manually?

**Comment by RoonMoonlight** [comment]
> Why not just have a server API for servers to ban it manually?

Because most servers won't allow using AxolotlClient if that feature is present on the mod, for example Mineplex disallowed the entire client like Badlion before, because it features the mod which gives you unfair advantage

For my idea, it is best to seperate freelook into other mod for people who still wish to use that feature later

**Comment by TheKodeToad** [comment]
> > Why not just have a server API for servers to ban it manually?
> 
> Because most servers won't allow using AxolotlClient if that feature is present on the mod, for example Mineplex disallowed the entire client like Badlion before, because it features the mod which gives you unfair advantage
> 
> For my idea, it is best to seperate freelook into other mod for people who still wish to use that feature later

Mineplex only disallowed Lunar Client afaik. This was due to some of its inconsistencies with vanilla could not be toggled by the user *or server*.

**Comment by RoonMoonlight** [comment]
> Mineplex only disallowed Lunar Client afaik. This was due to some of its inconsistencies with vanilla could not be toggled by the user _or server_.

Sorry I forgot which mod was banned since I don't play on that server anymore... And I heard there is the case which bans entire mod if the mod have features which gains unfair advantage, even it has ability to disable that feature on settings

And this is the most reason why I am afraid to keep that freelook feature exist on AxolotlClient, when I report someone with AxolotlClient it would get self-report banned instead of that person

So there is two ways, removing it entirely or seperating freelook into other mods

**Comment by TheKodeToad** [comment]
If you take Hypixel as an example, they allow Lunar and Badlion client and simply send the required packets to turn off Freelook and AutoText (or restrict it in the case of Badlion).

**Comment by RoonMoonlight** [comment]
> If you take Hypixel as an example, they allow Lunar and Badlion client and simply send the required packets to turn off Freelook and AutoText (or restrict it in the case of Badlion).

Yeah that would work, but what about some of servers not even trying to add API to disable specific features and banning AxolotlClient for just having that freelook feature?

**Comment by TheKodeToad** [comment]
> Yeah that would work, but what about some of servers not even trying to add API to disable specific features and banning AxolotlClient for just having that freelook feature?

Well if they're not messing with packets at all, they can't really ban Axolotl Client. It technically is possible to detect though.

**Comment by RoonMoonlight** [comment]
Well, now moving to [this issue](https://github.com/AxolotlClient/AxolotlClient-mod/issues/13) for now (I made suggestion on that issue)

**Comment by TheKodeToad** [comment]
Since I don't really have any authority of what happens with this project the developer/maintainer may still consider this. Maybe I should have made that clearer from the start.

**Comment by RoonMoonlight** [comment]
> Since I don't really have any authority of what happens with this project the developer/maintainer may still consider this. Maybe I should have made that clearer from the start.

Okay then, will reopen this one (just in case)

**Comment by moehreag** [comment]
Currently there is a system in place to prevent you from using certain features (e.g. Freelook) on certain servers where we know that their usage is prohibited. The code (and servers) for this are located [here](https://github.com/AxolotlClient/AxolotlClient-mod/blob/c1257c1bb67509a966af1f99bbdffd206dfde89d/src/main/java/io/github/axolotlclient/util/FeatureDisabler.java#L46) and this is how it looks like: 
![image](https://user-images.githubusercontent.com/85403855/210221218-94a159aa-1e9b-40de-a409-aab397dd47a4.png) (on hypixel in this case). 

If you feel like server owners should have direct control over what features are allowed, an API for this may still be added.

I don't think that big servers like hypixel and mineplex would bother to implement an API for a pretty niche mod, therefore the system shown above was implemented.

The part you of the modrinth description you cited was written before the feature mentioned above was added.

**Comment by moehreag** [comment]
A small API for servers to disable certain features (e.g. Freelook) is now added. If more/other features are needed to be disabled, please let us know. 

If you need help with implementing such a system on the server, please ping us as well.
