### ISSUE TITLE
Crashes on multiplayer

### ISSUE THREAD

**Issue by catvin82** [moehreag/AxolotlClient-branding#60]
Axolotl Client 1.19.3 crashes when joining multiplayer... tell me any info you need

**Comment by moehreag** [comment]
A crash log would be nice to have if you could give me that

**Comment by catvin82** [comment]
ok, 
[crash-2023-01-29_13.46.12-client.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/10530697/crash-2023-01-29_13.46.12-client.txt)

**Comment by moehreag** [comment]
Sadly I am unable to reproduce this crash. If you want to fix the crash temporarily, turn off the HotbarHUD.
Otherwise I could maybe try to debug it further if you give me a mixin export of the instance where the crash occurs.

**Comment by catvin82** [comment]
Okay, thanks. I am just using a lot of mods, It could be an incompatiblity or something to to with quilt.

**Comment by catvin82** [comment]
also can you just change the settings directly form the file or is there some safeguard

**Comment by moehreag** [comment]
it's probably an incompatibility with some other mod. Yes you can go in the settings file and mess with it if you want, but just changing the option before joining a world (from the title screen) should work as well.

**Comment by catvin82** [comment]
Ok, thank you

**Comment by catvin82** [comment]
Also Ty for making this great mod!
