### ISSUE TITLE
Chinese Translations broken on 3.0.1

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#63]
Needs more test

**Comment by moehreag** [comment]
feel free to join the discord to discuss these things before the release, that would also allow me to ping you whenever the translations should be updated.

**Comment by HowardZHY** [comment]
I think it needs to be formatted as /u unicode

**Comment by moehreag** [comment]
https://github.com/AxolotlClient/AxolotlClient-mod/commit/e07aeabeb350af1d941833b5883d373ced7e3f3b

**Comment by HowardZHY** [comment]
thanks let me try it

**Comment by HowardZHY** [comment]
I'll update translations someday
