### ISSUE TITLE
Fabric version for 1.19.2

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [moehreag/AxolotlClient-branding#67]
title

**Comment by moehreag** [comment]
I wonder why you can't use quilt, your fabric mods work with it

**Comment by TheKodeToad** [comment]
Most should do, yes. A Fabric version requires *more* maintainance so it's unlikely to happen.

**Comment by IdkWhatToCallMe123** [comment]
> I wonder why you can't use quilt, your fabric mods work with it

Oh didn't know that lol
thanks anyways ig

oops closed the issue as completed didnt mean to do that
