### ISSUE TITLE
Fabric for 1.19.4

### ISSUE THREAD

**Issue by Zynotix** [moehreag/AxolotlClient-branding#71]
I want to now if this client will ever come to 1.19.4 with fabric and not just Quilt because this mod looks great! I just can't get it for fabric on newer versions. :(
Thank you!

**Comment by TheKodeToad** [comment]
See https://github.com/AxolotlClient/AxolotlClient-mod/issues/67#issuecomment-1468732724... i don't think it's happening!

**Comment by moehreag** [comment]
Short answer: no.
Long answer: The additional work required to make everything work on fabric while also not supporting a valuable project in the meantime makes this not worth it, in my opinion. This means there will be no official port to fabric, but the good news is that most (if not all) of your fabric mods work on Quilt. While we can't (and won't) stop you from porting it yourself (provided the license isn't violated), you can save yourself quite a bit of work by just switching to Quilt, and in case you need help, either ask in our discord server (the link is in the README) or (if it's an issue regarding Quilt) in Quilt's discord server.
