### ISSUE TITLE
Crash with Legacy LWJGL3

### ISSUE THREAD

**Issue by ghost** [moehreag/AxolotlClient-branding#73]
When unfocused fps limiter is enabled or menu blur, the game crashes with [Legacy LWJGL3](https://github.com/Zarzelcow/legacy-lwjgl3/) on Minecraft 1.8.9, Fabric Loader 0.14.19, API Version 1.9.1 

Unfocused FPS crash log
https://mclo.gs/o8TpvhP
Menu Blur crash log
https://mclo.gs/9KKHe6g

**Comment by moehreag** [comment]
Well, there are multiple issues in your logs. Firstly, you probably didn't read legacy-lwjgl3's Readme completely, which states that you need to compile it yourself to get a remapped mod (this is very likely to be the cause for the ClassNotFound exception in the log). Secondly, there are just some functions that got moved, changed, or removed in lwjgl3 compared to lwjgl2. This is what crashes your game in the end.

**Comment by ghost** [comment]
I recompiled it and it still crashes

**Comment by moehreag** [comment]
You probably didn't read the second half of my answer. It crashes because the mod tries to use functions that aren't present in lwjgl3 but are in lwjgl2. Changing this would require a hard dependency on legacy-lwjgl, which I don't think I particularly want.
