### ISSUE TITLE
crosshair HUD module bug

### ISSUE THREAD

**Issue by xenonslime** [moehreag/AxolotlClient-branding#74]
Hi, it's nothing big (I think).
Enabling the **crosshair HUD** module **disables/removes the background** of every other HUD module (like real time, fps counter, tps, scoreboard, ...)
When you disable the crosshair HUD module evrything reverts into the normal state.
(thanks for your great work btw 👍 )

**Comment by moehreag** [comment]
Hey, thanks for reporting this bug! Could you please also provide the minecraft version this affects? It would help a lot with fixing it.

**Comment by xenonslime** [comment]
Oh, I found something.
It's the aftereffect of "**Apply Blending**" option being on. When I set it to off the backgrounds appear.
So I guess it's still a bug?

**Comment by xenonslime** [comment]
> Hey, thanks for reporting this bug! Could you please also provide the minecraft version this affects? It would help a lot with fixing it.

Yeah sure, it's Minecraft 1.19.4, Quilt mod loader.
