### ISSUE TITLE
Scoreboard module background bug

### ISSUE THREAD

**Issue by xenonslime** [moehreag/AxolotlClient-branding#75]
I'm so sorry it's me again...
When enabling the background option for the scoreboard HUD module it messes up other modules (see pictures below).

Scoreboard HUD background off:
![hud_module_background_disabled](https://github.com/AxolotlClient/AxolotlClient-mod/assets/53369408/a7599c1d-07b8-4539-acc0-1c1c9cc51221)

Scoreboard HUD background on:
![hud_module_background_enabled](https://github.com/AxolotlClient/AxolotlClient-mod/assets/53369408/646f8db9-069c-41f8-a3e8-882de9313f6b)
Also the background removes the text color?

Minecraft 1.19.4, Quilt Mod launcher

P.S.: Keep up the great work 👍 
P.P.S.: Don't sweat it. Take your time. 😸

**Comment by moehreag** [comment]
It was a blending issue.. (as well); don't worry about our (mental) health, it's already about as bad as it can get
