### ISSUE TITLE
 Crash with https://modrinth.com/mod/ok-zoomer

### ISSUE THREAD

**Issue by gitdrug** [moehreag/AxolotlClient-branding#81]
Minecraft Version: 1.20.1
Mod List
Ok Zoomer
AxolotlClient
ModMenu
Quilted Fabric API
(I think this crash is because this mod also has a zoom, this incompatibility doesn't really matter for the same reason I think its crashing)

**Comment by gitdrug** [comment]
Crash Report
[crash-2023-07-06_06.27.28.6190-quilt_loader.txt](https://github.com/AxolotlClient/AxolotlClient-mod/files/11968692/crash-2023-07-06_06.27.28.6190-quilt_loader.txt)

**Comment by moehreag** [comment]
This happens because OKZoomer uses Quilt Config which had changes in the latest betas of Quilt Loader and therefor OKZoomer is breaking with it, it's totally unrelated to this mod. If you want to temporarily fix this, downgrade Quilt Loader to a stable release.
