### ISSUE TITLE
Consider making other loader version of AxolotlClient

### ISSUE THREAD

**Issue by RoonMoonlight** [moehreag/AxolotlClient-branding#92]
The recent Quilt status is following:
https://github.com/Fabulously-Optimized/fabulously-optimized/issues/257#issuecomment-1651154622

tl:dr;
* Quilt adds their own telemetry in the launcher, and it also collects information that shouldn't be collected

Though I respect the reason of having a Quilt as mod loader but I feel I don't wanna use Quilt anymore...

Can you consider making alternatives loader version such as Fabric? If not well... Gotta find alternatives once again

(Sorry if I provided wrong information, I am trying my best to fix wrong info as many as possible)

**Comment by MenacingPerson** [comment]
I agree with this. Not only this,  but quilt also sometimes lags behind on updates to it's fabric loader and api impl, so mods may require a newer version of fabric and it's api which is not available on quilt, causing you to need to use old versions or not use that mod at all.

**Comment by Fnige** [comment]
I will point out:

> Quilt adds their own telemetry in the launcher, and it also collects information that shouldn't be collected

This got removed at least

> Due to recent incident regarding of Telemetry from Quilt Community, 11 non-developers left the Quilt Team

And this was for an entirely different reason lol

> so mods may require a newer version of fabric and it's api which is not available on quilt

You can fix this with dependency overrides

**Comment by MenacingPerson** [comment]
> You can fix this with dependency overrides

Yeah. Amazing idea. Not like different fapi versions might have different functionality, or there might be another difference in the versions. And I would, except quilt overrides are way more complex than fabric ones. But that's not really relevant here.

**Comment by Fnige** [comment]
> Yeah. Amazing idea. Not like different fapi versions might have different functionality, or there might be another difference in the versions. And I would, except quilt overrides are way more complex than fabric ones. But that's not really relevant here.

Most times they dont, and usually qfapi updates are quick enough for this to not matter too much anyway (recently is an exception due to the drama that happened)

And yeah sadly quilt overrides are more complex... it is still learnable but sadly it isnt what fabric has (iirc they cant do what fabric for some reason which we forgot)

**Comment by MenacingPerson** [comment]
Currently both indium and continuity on 1.19.4 require a newer fapi version than what quilt provides.

Also yeah quilt has more drama than fabric :shrug:

**Comment by Oliver-makes-code** [comment]
> Due to recent incident regarding of Telemetry from Quilt Community, 11 non-developers left the Quilt Team

This is complete misinformation.

As someone who used to be on the quilt team I (and I assume most of the others) left due to the strees of changing management (which is natural when stuff like that changes)

You need to do more research before spreading false information to drive a point

**Comment by RoonMoonlight** [comment]
> This is complete misinformation.
> 
> As someone who used to be on the quilt team I (and I assume most of the others) left due to the strees of changing management (which is natural when stuff like that changes)
> 
> You need to do more research before spreading false information to drive a point

By the way, I've attached the link to the reference so you can check what is true (And that is why I stated that there might be wrong information)

I'm sorry, will go remove it asap

**Comment by RoonMoonlight** [comment]
Closing this because my explanation skill is bullshit.
