### ISSUE TITLE
Zoom not working with optifabric

### ISSUE THREAD

**Issue by ChameleonCiskoCZ** [moehreag/AxolotlClient-branding#93]
I'm using this client along with optifabric on legacy fabric (1.8.9), i want to use the zoom from the client because it is better, but i can't use it when i have optifine installed

**Comment by moehreag** [comment]
This is because OptiFine replaces the class the zoom injects to work. Compatibility may be added a later date, but is currently not being worked on for obvious reasons (OptiFine being a really, really invasive mod).

**Comment by TheKodeToad** [comment]
if it's not crashing, you could just try unbinding optifine's zoom...

**Comment by moehreag** [comment]
> if it's not crashing, you could just try unbinding optifine's zoom...

No, that doesn't work because OF just straight up replaces the entire GameRenderer (means different class ergo no injection by our zoom implementation)

**Comment by TheKodeToad** [comment]
huh. last time I checked Ok Zoomer worked fine (yes it was 2021 lol)

**Comment by moehreag** [comment]
> huh. last time I checked Ok Zoomer worked fine (yes it was 2021 lol)

this is 1.8.9.

**Comment by TheKodeToad** [comment]
Oh - I sometimes wish I could read

**Comment by ghost** [comment]
silly kodetoad
