### ISSUE TITLE
Bedwars Bugs

### ISSUE THREAD

**Issue by DarkKronicle** [moehreag/AxolotlClient-branding#98]
Been playing quite a bit of bedwars the last two weeks. Here are some bugs I have found.

- [Tablist color blending](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsGame.java#L466) does not work currently. I can't tell if it's an int conversion issue or smth. It is white from 1-20, and red just at 0. It would also probably be good to check if health is above 20, and then blend with a gold/yellow color because the player is gapped.
- [Levelhead](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/mixin/EntityRendererMixin.java#L87) displays "level" even if it's bedwars stars.
- [This `Getter`](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsPlayer.java#L39) is unnecessary (`@Data` class)
- I think [this](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsPlayer.java#L96) returns null if there is no API, so it doesn't properly add fake stats to the players itself. When I was playing without an API key, pretty much no game stats were working. Game stats levelhead didn't work, on team death stats. I think this is the root cause.

**Comment by moehreag** [comment]
> Been playing quite a bit of bedwars the last two weeks. Here are some bugs I have found.
> 
>     * [Tablist color blending](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsGame.java#L466) does not work currently. I can't tell if it's an int conversion issue or smth. It is white from 1-20, and red just at 0. It would also probably be good to check if health is above 20, and then blend with a gold/yellow color because the player is gapped.
> 
>     * [Levelhead](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/mixin/EntityRendererMixin.java#L87) displays "level" even if it's bedwars stars.
> 
>     * [This `Getter`](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsPlayer.java#L39) is unnecessary (`@Data` class)
> 
>     * I think [this](https://github.com/AxolotlClient/AxolotlClient-mod/blob/08b92433fdc27e66304d7a55107c9827925fbd17/1.8.9/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsPlayer.java#L96) returns null if there is no API, so it doesn't properly add fake stats to the players itself. When I was playing without an API key, pretty much no game stats were working. Game stats levelhead didn't work, on team death stats. I think this is the root cause.

- Tablist color blending does not work: This just seems like an issue caused by a lack of parentheses. I hope this fixes it.
- It displays the "Level: " text whenever it's displayed by the levelhead module (All of Network, Bedwars and Skywars are levels after all, aren't they?). While in a game, it should not unless the respective option is disabled.
- Yes it is, it'll get removed.
- This should be solved now. If it isn't, make sure your hypixel API key is still valid.

**Comment by DarkKronicle** [comment]
> It displays the "Level: " text whenever it's displayed by the levelhead module (All of Network, Bedwars and Skywars are levels after all, aren't they?). While in a game, it should not unless the respective option is disabled.

Usually in bedwars it's just referred to as stars. Tho it could be kept as levels and just append the ☆ to the value. I think that would be best.

> This should be solved now. If it isn't, make sure your hypixel API key is still valid.

Awesome. The main issue is when I didn't have an API key/invalid one.

**Comment by DarkKronicle** [comment]
I'll give it a test later today/tomorrow morning.

**Comment by DarkKronicle** [comment]
Tested it out. Now the tablist color blending has the reverse problem. It's always red below 20.

**Comment by moehreag** [comment]
> Tested it out. Now the tablist color blending has the reverse problem. It's always red below 20.

should no longer occur now
